app/urls.py
from django.urls import path
from . import views as app_views

app_name = 'app'
urlpatterns = [
    path('dashboard/',app_views.IndexView.as_view(),name = 'home'),
    path('home/analysis/',app_views.IndexAnalysisView.as_view(),name = 'home_analysis'),
    path('home/analysis/general/',app_views.GeneralAnalysisView.as_view(),name = 'general_analysis'),
    path('inventory/',app_views.InventoryView.as_view(),name = 'inventory'),
    path('inventory/create/',app_views.InventoryCreateView.as_view(),name = 'inventory_create'),
    path('inventory/<int:pk>/detail/',app_views.InventoryDetailView.as_view(),name = 'inventory_detail'),
    path('inventory/<int:pk>/edit/',app_views.InventoryEditView.as_view(),name = 'inventory_edit'),
    path('inventory/search/',app_views.InventorySearchView.as_view(),name = 'inventory_search'),
    path('inventory/analysis/',app_views.InventoryAnalysisView.as_view(),name = 'inventory_analysis'),
    path('inventory/delete/',app_views.InventoryDeleteView.as_view(),name = 'inventory_delete'),
    path('transactions/',app_views.TransactionsView.as_view(),name = 'transactions'),
    path('transaction/create/',app_views.TransactionCreateView.as_view(),name = 'transaction_create'),
    path('staffs/',app_views.StaffsListView.as_view(),name = 'staffs'),
    path('staffs/add/',app_views.StaffAddView.as_view(),name = 'staff_add'),
    path('staffs/delete/',app_views.StaffDeleteView.as_view(),name = 'staff_delete'),
    path('product/search/',app_views.SearchProductView.as_view(),name = 'search_product'),
    path('transaction/save/',app_views.SaveTransactionView.as_view(),name = 'transaction_save'),
    path('analysis/',app_views.AnalysisView.as_view(),name = 'analysis'),
    path('analysis/custom/<str:type>/',app_views.CustomAnalysisView.as_view(),name = 'custom_analysis'),
    path('analysis/generate/custom/',app_views.GenerateCustomAnalysisView.as_view(),name = 'generate_custom_analysis'),
    path('sales/reports/',app_views.SalesReportView.as_view(),name = 'sales_report'),
    path('sales/report/template/<str:duration>/',app_views.SalesReportTemplateView.as_view(),name = 'sales_report_template')
]

company/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views as company_views

app_name = 'company'
urlpatterns = [
    path('',company_views.CompanyLoginView.as_view(),name = 'login'),
    path('logout/',LogoutView.as_view(),name = 'logout'),
    path('company/profile/',company_views.CompanyProfileView.as_view(),name = 'profile')
]

stark_pos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('company.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

app/models.py
import os
from PIL import Image
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class CompanyDetails(models.Model):
    """ This class stores all the details about a company """
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    name = models.CharField(max_length = 100)
    image = models.ImageField(upload_to = 'company_logo',default = "default_company_logo.png")
    mobile1 = models.CharField(max_length = 30)
    mobile2 = models.CharField(max_length = 30, null = True, blank  = True)
    location = models.CharField(max_length = 200)

    def __str__(self):
        return f"{self.name}"

    def save(self):
        super().save()
        img = Image.open(self.image.path)
        img = img.resize((500,400))
        img.save(self.image.path)

    def delete(self):
        img = self.image.path
        super().delete()
        os.remove(img)

class Product(models.Model):
    """ This class stores all the details of a product """
    company = models.ForeignKey(CompanyDetails,on_delete = models.CASCADE)
    name = models.CharField(max_length = 200)
    unit_price = models.DecimalField(decimal_places = 2, max_digits = 65,default = 0.00)
    quantity = models.PositiveIntegerField(default = 1)
    image = models.ImageField(upload_to = f"product_images",default = 'product_logo.png')

    def __str__(self):
        return f"{self.company.name} - {self.name}"

    def save(self):
        super().save()
        if self.image.url != '\media\product_logo.png':
            img = Image.open(self.image.path)
            img = img.resize((500,500))
            img.save(self.image.path)

    def delete(self):
        image = self.image
        super().delete()
        if image.url != '/media/product_logo.png':
            os.remove(image.path)

    def get_absolute_url(self):
        return reverse('app:inventory')



class StockOverview(models.Model):
    """ This class stores all the stock for a company """
    company = models.OneToOneField(CompanyDetails,on_delete = models.CASCADE)
    stock = models.PositiveIntegerField(default = 0)
    stock_sold = models.PositiveIntegerField(default = 0)

    def __str__(self):
        return f"{self.company.name} stock overview"

    def stock_left(self):
        return self.stock - self.stock_sold

class RevenueAnalysis(models.Model):
    """ This class stores the total revernu made for each day """
    company = models.ForeignKey(CompanyDetails,on_delete = models.CASCADE)
    total_revenue = models.DecimalField(max_digits = 1000,decimal_places = 2,default = 0)
    date = models.DateField(default = timezone.now)

    def __str__(self):
        return f"Total revenue for {self.company.name} on {self.date.strftime('%A')}, {self.date}"


    class Meta:
        ordering = ['-date']


class ProductData(models.Model):
    """ This class stores all data relating to a product which will be used for analysis """
    company = models.ForeignKey(CompanyDetails,on_delete = models.CASCADE)
    product = models.ForeignKey(Product,on_delete = models.CASCADE)
    date = models.DateField(default = timezone.now,blank = True)
    quantity = models.PositiveIntegerField(default = 0)

    def __str__(self):
        return f"{self.company.name} - {self.product.name} data for {self.date.strftime('%A')}. {self.date}"


    class Meta:
        ordering = ['-date','product']

class Transaction(models.Model):
    """ This class stores all the transactions relating to a company """
    company = models.ForeignKey(CompanyDetails,on_delete = models.CASCADE)
    total = models.DecimalField(max_digits = 65,decimal_places = 2)
    date = models.DateField(default = timezone.now)

    def __str__(self):
        return f"{self.company.name} transaction {self.id}"

    class Meta:
        ordering = ['-date']


class TransactionItem(models.Model):
    """ This class stores all the items for a single transaction """
    transaction = models.ForeignKey(Transaction,on_delete = models.CASCADE)
    product_name = models.CharField(max_length = 200)
    product_price = models.DecimalField(decimal_places = 2,max_digits = 1000,default = '0.00')
    product_quantity = models.PositiveIntegerField(default = 1)
    total = models.DecimalField(decimal_places = 2,max_digits = 1000,default = '0.00')

    def __str__(self):
        return f"{self.transaction.company.name} transaction {self.transaction.id} item"


class Staff(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,default = None,null=True)
    company = models.ForeignKey(CompanyDetails,on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.company.name} staff {self.id}"

app/templates/app/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="Developer" content="Stark Tech Solutions"/>
    <meta name="Email" content="ebenezeroffei@outlook.com"/>
    <meta name = 'viewport' content = 'width=device-width,initial-scale=1.0'>
    <link rel="stylesheet" href="{% static 'app\bootstrap.min.css' %}">
    <style>
        /* Navbar For Snall Screen */
        nav{
            background: #42506b;
            color: white;
            padding: 8px 0px 8px 60px;
            position: fixed;
            width: 100%;
            top: -500px;
            transition: top .3s ease-in-out;
            z-index: 2;

        }
        /* Side Menu Designs */
        ::-webkit-scrollbar{
            width: 8px;
        }
        ::-webkit-scrollbar-thumb{
            background: #42506b;
        }
        #side-menu{
            width: 180px;
            height: 100vh;
            position: fixed;
            top: 0px;
            left: 0px;
            background: #42506b;
            text-align: center;
            color: white;
            transition: all .3s ease-in-out;
        }
        
        #side-menu > ul{
            margin: auto;
            padding: 0px;
            list-style: none;
            text-align: left;
        }
        #side-menu > ul > li > a{
            display: block;
            padding: 8px 15px;
            color: white;
            position: relative;
/*            background: red;*/
        }
        #side-menu > ul > li > a:hover{
            text-decoration: none;
            background: #333c59;
        }
        #side-menu > ul > li:last-child > a{
            color: crimson;
        }
        /* Active Section */
        #side-menu  #active::before{
            content: '';
            display: block;
            background: white;
            width: 5px;
            border-radius: 0px 5px 5px 0px;
            height: 100%;
            position: absolute;
            top: 0px;
            left: 0px;
        }
        /* Main Content */
        #main-content{
            width: calc(100% - 200px);
            height: 300px;
            position: relative;
            top: 10px;
            left: 190px;
            transition: all 0.3s ease-in-out;
        }
        /* Loader */
        #loader{
            background-color: rgba(0,0,0,.6);
            width: 100%;
            height: 100vh;
            position: absolute;
            top: 0;
            z-index: 3;
            margin: 0;
            text-align: center;
            display: none;
        }
        #loader > p{
            width: 150px;
            height: 150px;
            margin: auto;
            margin-top: 200px;
            background: transparent;
            border: thick solid white;
            border-radius: 50%;
            border-left: thick solid transparent;
            border-right: thick solid transparent;
            text-align: center;
            animation: rotate 3s infinite ease-in-out forwards;
        }
        #loader > p > span{
            margin-top: 20px;
            display: inline-block;
            width: 100px;
            height: 100px;
            border: thick solid white;
            border-top: thick solid transparent;
            border-bottom: thick solid transparent;
            border-radius: 50%;
            animation: rotate 3s infinite  ease-in-out forwards;
        }

        @keyframes rotate{
            0%{
                transform: rotate(0deg);
            }
            50%{
                transform: rotate(360deg);
            }
            100%{
                transform: rotate(0deg);
            }
        }
        /* Media Query From 0 - 600px */
        @media only screen and (max-width:600px){
            /* Navbar */
            nav{
                top: 0px;
            }
            /* Side Menu */
            #side-menu{
                width: 55px;
            }


            #side-menu > img, #side-menu > h5,#side-menu > ul > li > a > span, #side-menu hr{
                display: none;
            }
            #side-menu > ul {
                margin-top: 100px;
            }
            /* Main Content */
            #main-content{
                top: 75px;
                left: 65px;
                width: calc(100% - 75px);
            }

        }
    </style>
    {% block head %}
    {% endblock %}
</head>
<body>
<!-- Loader -->
<div id="loader">
    <p>
        <span></span>
    </p>
</div>
 <!-- Navbar which displays when the size of the screen becomes small -->
  <nav>
      <!-- Company Image -->
      <img src="{{ user.companydetails.image.url }}" style ='background: white;width: 50px;border-radius: 50%;height: 50px;border: 3px solid rgba(0,0,0,.2);' alt="">
       <!-- Company Name -->
       <h5 style="font-weight: 400;display: inline-block;margin-left: 10px;">{{ user.companydetails.name }}</h5>
  </nav>
   <div id="side-menu">
       <!-- Company Image -->
       <img src="{{ user.companydetails.image.url }}" style ='background: white;width: 130px;border-radius: 50%;height: 130px;border: 6px solid rgba(0,0,0,.2);margin-top: 20px' alt="">
       <!-- Company Name -->
       <h5 style="font-weight: 400;">{{ user.companydetails.name }}</h5>
       <hr/>
       <!-- Sections -->
       <ul>
           <li><a href="{% url 'app:home' %}" id="active">
              <img src="{% static 'app/images/dashboard.svg' %}" style="width: 25px;position: relative;bottom:4px" alt="">
               <span>Dashboard</span>
            </a></li>
           <li><a href="{% url 'app:inventory' %}">
              <img src="{% static 'app/images/inventory.svg' %}" style="width: 25px;position: relative;bottom:4px" alt="">
               <span>Inventory</span>
            </a></li>
            <li><a href="{% url 'app:staffs' %}">
              <img src="{% static 'app/images/staffs.png' %}" style="width: 25px;position: relative;bottom:4px" alt="">
               <span>Staffs</span>
            </a></li>
           <li><a href="{% url 'app:analysis' %}">
              <img src="{% static 'app/images/analysis.svg' %}" style="width: 25px;position: relative;bottom:4px" alt="">
               <span>Analysis</span>
            </a></li>
           <li><a href="{% url 'app:sales_report' %}">
              <img src="{% static 'app/images/sales.svg' %}" style="width: 25px;position: relative;bottom:4px" alt="">
               <span>Sales</span>
            </a></li>
            <li><a href="{% url 'company:profile' %}">
              <img src="{% static 'app/images/profile.svg' %}" style="width: 25px;position: relative;bottom:4px" alt="">
              <span>Profile</span>
            </a></li>
           <li><a href="{% url 'company:logout' %}">
              <img src="{% static 'app/images/logout.svg' %}" style="width: 25px;position: relative;bottom:4px" alt="">
               <span>Logout</span>
            </a></li>
       </ul>
       
   </div>
   <div id="main-content">
       {% block content %}
       {% endblock %}
   </div>
    <script src="{% static 'app\jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'app\bootstrap.bundle.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>
</html>

app/templates/app/custom_transactions.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="Developer" content="Stark Tech Solutions"/>
    <meta name="Email" content="ebenezeroffei@outlook.com"/>
    <meta name = 'viewport' content = 'width=device-width,initial-scale=1.0'>
    <link rel="stylesheet" href="{% static 'app\bootstrap.min.css' %}">
    <title>Transactions</title>
    <style>
        /* Navbar For Snall Screen */
        nav{
            background: #42506b;
            color: white;
            padding: 8px 0px 8px 60px;
            position: fixed;
            width: 100%;
            top: -500px;
            transition: top .3s ease-in-out;
            z-index: 2;

        }
        /* Side Menu Designs */
        ::-webkit-scrollbar{
            width: 8px;
        }
        ::-webkit-scrollbar-thumb{
            background: #42506b;
        }
        #side-menu{
            width: 180px;
            height: 100vh;
            position: fixed;
            top: 0px;
            left: 0px;
            background: #42506b;
            text-align: center;
            color: white;
            transition: all .3s ease-in-out;
        }
        
        #side-menu > ul{
            margin: auto;
            padding: 0px;
            list-style: none;
            text-align: left;
        }
        #side-menu > ul > li > a{
            display: block;
            padding: 8px 15px;
            color: white;
            position: relative;
/*            background: red;*/
        }
        #side-menu > ul > li > a:hover{
            text-decoration: none;
            background: #333c59;
        }
        #side-menu > ul > li:last-child > a{
            color: crimson;
        }
        /* Main Content */
        #main-content{
            width: calc(100% - 200px);
            height: 300px;
            position: relative;
            top: 10px;
            left: 190px;
            transition: all 0.3s ease-in-out;
        }
        /* Loader */
        #loader{
            background-color: rgba(0,0,0,.6);
            width: 100%;
            height: 100vh;
            position: absolute;
            top: 0;
            z-index: 3;
            margin: 0;
            text-align: center;
            display: none;
        }
        #loader > p{
            width: 150px;
            height: 150px;
            margin: auto;
            margin-top: 200px;
            background: transparent;
            border: thick solid white;
            border-radius: 50%;
            border-left: thick solid transparent;
            border-right: thick solid transparent;
            text-align: center;
            animation: rotate 3s infinite ease-in-out forwards;
        }
        #loader > p > span{
            margin-top: 20px;
            display: inline-block;
            width: 100px;
            height: 100px;
            border: thick solid white;
            border-top: thick solid transparent;
            border-bottom: thick solid transparent;
            border-radius: 50%;
            animation: rotate 3s infinite  ease-in-out forwards;
        }

        @keyframes rotate{
            0%{
                transform: rotate(0deg);
            }
            50%{
                transform: rotate(360deg);
            }
            100%{
                transform: rotate(0deg);
            }
        }
        /* Media Query From 0 - 600px */
        @media only screen and (max-width:600px){
            /* Navbar */
            nav{
                top: 0px;
            }
            /* Side Menu */
            #side-menu{
                width: 55px;
            }


            #side-menu > img, #side-menu > h5,#side-menu > ul > li > a > span, #side-menu hr{
                display: none;
            }
            #side-menu > ul {
                margin-top: 100px;
            }
            /* Main Content */
            #main-content{
                top: 75px;
                left: 65px;
                width: calc(100% - 75px);
            }

        }

        /* Media query from 0 - 770px */
        @media only screen and (max-width:770px){
            .transaction-total{
                display: none;
            }
        }
    </style>
</head>
<body>
<!-- Loader -->
<div id="loader">
    <p>
        <span></span>
    </p>
</div>
 <!-- Navbar which displays when the size of the screen becomes small -->
  <nav>
      <!-- Company Image -->
      <img src="{{ user.staff.company.image.url }}" style ='background: white;width: 50px;border-radius: 50%;height: 50px;border: 3px solid rgba(0,0,0,.2);' alt="">
       <!-- Company Name -->
       <h5 style="font-weight: 400;display: inline-block;margin-left: 10px;">{{ user.staff.company.name }}</h5>
  </nav>
   <div id="side-menu">
       <!-- Company Image -->
       <img src="{{ user.staff.company.image.url }}" style ='background: white;width: 130px;border-radius: 50%;height: 130px;border: 6px solid rgba(0,0,0,.2);margin-top: 20px' alt="">
       <!-- Company Name -->
       <h5 style="font-weight: 400;">{{ user.staff.company.name }}</h5>
       <hr/>
       <!-- Sections -->
       <ul>
           <li><a href="{% url 'app:transactions' %}">
              <img src="{% static 'app/images/transaction.svg' %}" style="width: 25px;position: relative;bottom:4px" alt="">
               <span>Transactions</span>
            </a></li>
           <li><a href="{% url 'company:logout' %}">
              <img src="{% static 'app/images/logout.svg' %}" style="width: 25px;position: relative;bottom:4px" alt="">
               <span>Logout</span>
            </a></li>
       </ul>
       
   </div>
   <div id="main-content">
       <div class="container-fluid">
            <div class="d-flex justify-content-between">
            <h3>Transactions</h3>
            <div>
                    <a href = "{% url 'app:transaction_create' %}" class = 'btn btn-primary'> New Transaction </a>
            </div>
            </div>
            <hr/>
            <!-- Recent Transactions For Today -->
            <div class="card mt-3 mb-3">
                <div class="card-header">Transactions For Today <span class="badge badge-dark">{{total_transaction_for_today}}</span></div>
                <ul class = 'list-group'>
                    {% for transaction in transactions %}
                    <li class="list-group-item p-2">
                        <!-- Items, Prices and Quantity -->
                            <div class="row">
                                <div class="col-6 col-md-6">
                                    <p class="text-muted small">Items</p>
                                </div>
                                <div class="col-3 col-md-2">
                                    <p class="text-muted small text-center">Quantity</p>
                                </div>
                                <div class="col-3 col-md-2">
                                    <p class="text-muted small text-center">Unit Price<br/>GH&#8373;</p>
                                </div>
                                <div class="col-0 col-md-2">
                                    <p class="text-muted small text-center transaction-total">Total<br/>GH&#8373;</p>
                                </div>
                            </div>
                            {% for item in transaction.transactionitem_set.all %}
                                <div class="row">
                                    <div class="col-6 col-md-6">
                                        <p class="small m-auto">{{item.product_name}}</p>
                                    </div>
                                    <div class="col-3 col-md-2">
                                        <p class=" small text-center m-auto">{{item.product_quantity}}</p>
                                    </div>
                                    <div class="col-3 col-md-2">
                                        <p class=" small text-center m-auto">{{ item.product_price }}</p>
                                    </div>
                                    <div class="col-0 col-md-2">
                                        <p class=" small text-center m-auto transaction-total">{{ item.total }}</p>
                                    </div>
                                </div>
                            {% endfor %}
                            <!-- Total -->
                            <hr class = 'bg-dark'/>
                            <p class = 'mt-2 mb-0 text-secondary'>Total: <span class = 'text-primary'>GH&#8373; {{transaction.total}}</span></p>
                        </li>
                    {% empty %}
                        <h3 class="text-center text-muted my-5">
                            No Transactions Has Been Recorded For Today. <br>
                            <a href = "{% url 'app:transaction_create' %}" style="max-width: 300px;margin: auto;" class = 'd-block mt-3 btn btn-primary'> New Transaction </a>
                        </h3>
                {% endfor %}
                </ul>
            </div>
        </div>
   </div>
    <script src="{% static 'app\jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'app\bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'app/transaction.js' %}"></script>
    <script>
        transactionsInit();
//        calculateProfit();
    </script>
</body>
</html>

app/templates/app/inventory.html
{% extends 'app/base.html' %}
{% load static %}


{% block head %}
    <title>Inventory</title>
    <style>
        .card{
            transition: all .2s ease-in-out;
            position: relative
        }
        .card:hover{
            box-shadow: rgb(209, 209, 213) 0px 5px 15px;
        }
        .card > a:hover{
            text-decoration: none;
        }
        #add-product{
            font-size: 100px;
        }
        #search-inventory:focus{
            outline: none;
            border: thin solid #333c59;
            box-shadow: none;
        }
        .options{
            position: absolute;
            width: 100%;
            top: 202px;
        }
        .options > a, .options > span{
            display: block;
            text-align: center;
            transition: all .2s ease-in-out;
            cursor: pointer;
        }
        .options > a{
            background: darkseagreen;
            border: thin solid rgba(0,0,0,.125);
            color: white;
        }
        .options > a:hover{
            color: darkseagreen;
            background: white;
        }
        .options > span:hover{
            color: crimson;
            background: white;
        }
        .options > span{
            background-color:crimson;
            border: thin solid rgba(0,0,0,.125);
            color: white;
        }
        .options > a:hover{
            text-decoration: none;
        }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid">
       {% csrf_token %}
        <div class="d-flex justify-content-between">
            <h3>Inventory <span class="badge badge-info">{{total_inventory}}</span></h3>
            <div>
                 <a id="new-inventory-create-url" href="{% url 'app:inventory_create' %}" class = 'btn btn-primary'> New Inventory</a>
            </div>
        </div><hr>
		<!-- Inventory -->
        <div class="form-group">
            <input type="search" id="search-inventory" placeholder="Search Inventory" class="form-control">
        </div>
		{% if messages %}
            {% for message in messages %}
                <p class="alert alert-success">{{ message }}</p>
            {% endfor %}
        {% endif %}
        {% if products %}
            <div id="products" class="row">
                {% for product in products %}
                    <div class="col-6 col-sm-6 col-md-4 col-xl-3 mt-2">
                        <div class="card h-100">
                        <div class = 'options'>
                            <a href="{% url 'app:inventory_edit' product.pk %}">Edit</a>
                            <span id="{{product.id}}" class="delete-product">Delete</span>
                        </div>
                            <a href="{% url 'app:inventory_detail' product.pk %}">
                                <img src="{{ product.image.url }}" height="250px" class="card-img-top" alt="">
                                <div class="card-body p-2">
                                    <h6 class="text-dark" style="text-overflow: ellipsis;width: 100%;white-space: nowrap;overflow: hidden;">{{ product.name }}</h6>
                                    <p class="text-dark small m-auto">
                                    Quantity Left:
                                        <span class = 'text-primary'>{{ product.quantity }}</span>
                                    </p>
                                    <p class="text-dark small m-auto">
                                    Unit Price:
                                        <span class = 'text-primary'>GH&#8373; {{ product.unit_price }}</span>
                                    </p>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div id="no-products"></div>
        {% else %}
            <div id="no-products">
                <h3 class="text-muted text-center">You haven't added any product.</h3>
                <a href="{% url 'app:inventory_create' %}" style="width: 300px;margin: 20px auto;display: block;" class="btn btn-primary">New Product</a>
            </div>
        {% endif %}
        <!-- Modal For Deleting A Product -->
        <div class="modal fade" id="deleteProduct" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="deleteProductLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header text-light" style="background: crimson;">
                <h5 class="modal-title" id="deleteProductLabel">Delete Product</h5>
                <button type="button" class="close text-light" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                   Are you sure you want to delete this product?
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-info" id = 'cancel' data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id = 'delete'>Delete</button>
              </div>
            </div>
          </div>
        </div>
    </div>
{% endblock %}
{% block javascript %}
    <script src="{% static 'app/inventory.js' %}"></script>
    <script>
        inventoryInit();
        searchInventory("{% url 'app:inventory_search' %}","{% url 'app:inventory_detail' 1 %}","{% url 'app:inventory_edit' 1 %}");
        deleteProduct("{% url 'app:inventory_delete' %}")
    </script>
{% endblock %}